pipelines:
  default:
    - step:
        name: Build and test
        image: maven:3
        caches: 
          - maven
        script:
          - mvn -B clean verify

    - step:
        name: Create artifact
        script:
          - tar czfv application.tgz pom.xml src/
        artifacts:
          - application.tgz

    - step:
        name: Deploy to production
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: f155358c-7e3d-4659-9317-b268c09b0f7a
              HEROKU_APP_NAME: autoapps-landing
              ZIP_FILE: "application.tgz"